# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PlanetAirCnC' do
 
   pod 'Masonry'
   pod 'AFNetworking'
   pod 'MBProgressHUD'
   pod 'SDWebImage'
   pod 'YYModel'
   pod 'IQKeyboardManager'


  target 'PlanetAirCnCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PlanetAirCnCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
