# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AirCnCWallent' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

   pod 'Masonry'
   pod 'AFNetworking'
   pod 'MBProgressHUD'
   pod 'SDWebImage'
   pod 'YYModel'
   pod 'IQKeyboardManager'

  # Pods for AirCnCWallent

  target 'AirCnCWallentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AirCnCWallentUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
